# Generated by Django 4.1.7 on 2023-05-06 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0008_abrigo_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Zapatilla',
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='email',
            field=models.EmailField(default='default value', max_length=254),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='imagenCamiseta',
            field=models.ImageField(blank=True, default='default value', null=True, upload_to='ropa'),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.CharField(default='default value', max_length=40),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='nombre',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='default value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='telefono',
            field=models.IntegerField(default='default value'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.CharField(default='', max_length=500),
        ),
    ]
