# Generated by Django 4.1.7 on 2023-05-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_mensaje_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.abrigo'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatars/avatar.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
