# Generated by Django 4.1.7 on 2023-05-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_comentario_comentario_alter_avatar_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
    ]
