# Generated by Django 4.1.7 on 2023-05-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_remove_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='talla',
            field=models.CharField(default='default value', max_length=40),
        ),
    ]
