# Generated by Django 4.1.7 on 2023-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_camiseta_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='imagenCamiseta',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ropa'),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='talla',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='telefono',
            field=models.IntegerField(default=''),
        ),
    ]
