# Generated by Django 4.1.7 on 2023-05-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_alter_camiseta_email_alter_camiseta_imagencamiseta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
