# Generated by Django 4.1.7 on 2023-05-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_delete_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
